# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fcalc_np <- function(c_i, c_j) {
    .Call(`_disruptr_fcalc_np`, c_i, c_j)
}

fcalc_np_all <- function(neighbors, v, exp) {
    .Call(`_disruptr_fcalc_np_all`, neighbors, v, exp)
}

